version: 2

linters:
  default: all
  disable:
    - depguard  # not currently used
  settings:
    misspell:
      locale: US

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      reformat-tags: false
