version: '3.8'

services:
  node:
    image: quay.io/prometheus/node-exporter:v1.10.2
  promrelay:
    image: ghcr.io/hhromic/promrelay-exporter:v2.7.0
    networks:
      - default
      - metrics

networks:
  default: {}
  metrics:
    external: true
    name: metrics_default
