version: '3.8'

services:
  prometheus:
    image: quay.io/prometheus/prometheus:v3.7.3
    command: >-
      --config.file=/prometheus.yaml
      --storage.tsdb.path=/prometheus
    user: root
    configs:
      - prometheus.yaml
    ports:
      - 9090:9090
    volumes:
      - data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock

configs:
  prometheus.yaml:
    external: true
    name: metrics-prometheus-yaml

volumes:
  data: {}
